### ISSUE TITLE
自己紹介の文章修正依頼

### ISSUE THREAD

**Issue by yncat** [actlaboratory/site#1]
## 変更前
えんじ?にゃー。ウェブ系フィンテック企業でマイクロサービスの保守とか開発とかやっている。
小学生時代から数々のゲームを製作・公開してきており、ここ数年は東京ゲームショーへの出展などをきっかけに数々のメディアに取材されている。

## 変更後
ソフトウェアエンジニア。ウェブ系フィンテック企業でマイクロサービスの保守とか開発とかやっている。
小学生時代から数々のゲームを製作・公開してきており、ここ数年は東京ゲームショーへの出展などをきっかけに各種メディアに取材されている。

**Comment by yamahubuki** [comment]
やったかどうか忘れましたが、必要に応じて管理者メニューからお手続きください。
