### ISSUE TITLE
自己紹介の修正について

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/site#3]
完全に自己満足ですが僕の自己紹介の修正をお願いします。
修正後の自己紹介は以下。

アニメと電子機器が大好きな全盲の高校生。茨城県出身。<br>
				以前からプログラミングはやっていたがこの外出自粛期間のソフト制作ではまってしまい現在メインの趣味になっている。<br>
				その他電子工作や自作パソコンにも興味があったりする。<br>
				楽しむという目的でプログラミングをしているが自分の制作物をできるだけたくさんの人に使ってほしいと思う。<br>

自己紹介文は以上です。よろしくお願いします。

**Comment by yamahubuki** [comment]
やったかどうか忘れましたが、必要に応じて管理者メニューからお手続きください。
